---
__repository_default:
  - name: "{{ ansible_distribution_release }}"
    repository: "deb https://ftp.uni-stuttgart.de/ubuntu/ {{ ansible_distribution_release }} main restricted universe multiverse"
    deb822_uris: https://ftp.uni-stuttgart.de/ubuntu/
    deb822_components: main restricted universe multiverse
    deb822_signed_by: /usr/share/keyrings/ubuntu-archive-keyring.gpg
  - name: "{{ ansible_distribution_release }}-backports"
    repository: "deb https://ftp.uni-stuttgart.de/ubuntu/ {{ ansible_distribution_release }}-backports main restricted universe multiverse"
    deb822_uris: https://ftp.uni-stuttgart.de/ubuntu/
    deb822_components: main restricted universe multiverse
    deb822_signed_by: /usr/share/keyrings/ubuntu-archive-keyring.gpg
  - name: "{{ ansible_distribution_release }}-security"
    repository: "deb https://ftp.uni-stuttgart.de/ubuntu/ {{ ansible_distribution_release }}-security main restricted universe multiverse"
    deb822_uris: https://ftp.uni-stuttgart.de/ubuntu/
    deb822_components: main restricted universe multiverse
    deb822_signed_by: /usr/share/keyrings/ubuntu-archive-keyring.gpg
  - name: "{{ ansible_distribution_release }}-updates"
    repository: "deb https://ftp.uni-stuttgart.de/ubuntu/ {{ ansible_distribution_release }}-updates main restricted universe multiverse"
    deb822_uris: https://ftp.uni-stuttgart.de/ubuntu/
    deb822_components: main restricted universe multiverse
    deb822_signed_by: /usr/share/keyrings/ubuntu-archive-keyring.gpg
