---
operator_user: dragon
operator_user_id: 45000

operator_group: dragon
operator_group_id: 45000

operator_groups:
  - adm
  - sudo

operator_shell: /bin/bash

operator_authorized_keys: []

# NOTE: Use "mkpasswd --method=sha-512" to generate a password
# operator_password:

operator_sudo_nopasswd: true
