---
- name: Remove update-motd package
  become: true
  ansible.builtin.apt:
    name: update-motd
    state: absent
    lock_timeout: "{{ apt_lock_timeout | default(300) }}"

- name: Check if /etc/default/motd-news exists
  ansible.builtin.stat:
    path: /etc/default/motd-news
  register: default_motd_news_stat

- name: Disable the dynamic motd-news service
  become: true
  ansible.builtin.lineinfile:
    path: /etc/default/motd-news
    regexp: "^ENABLED="
    line: "ENABLED=0"
  when: default_motd_news_stat.stat.exists is defined and default_motd_news_stat.stat.exists

- name: Get all configuration files in /etc/pam.d
  ansible.builtin.find:
    paths: /etc/pam.d
    file_type: file
    contains: pam_motd.so
    read_whole_file: true
  register: etc_pam_motd

- name: Remove pam_motd.so rule
  become: true
  community.general.pamd:
    module_path: pam_motd.so
    control: optional
    type: session
    state: absent
    name: "{{ item.path | ansible.builtin.basename }}"
  loop: "{{ etc_pam_motd.files }}"

- name: Configure SSH to print the motd
  become: true
  copy:
    dest: /etc/ssh/sshd_config.d/60-motd.conf
    content: |
       PrintMotd yes
  notify: Reload sshd to make motd changes effective
  when: motd_show_ssh == true

- name: Configure SSH to not print the motd
  become: true
  file:
    path: /etc/ssh/sshd_config.d/60-motd.conf
    state: absent
  notify: Reload sshd to make motd changes effective
  when: motd_show_ssh != true

