---
##########################
# packages

kubectl_package_name: kubectl

##########################
# repository (arch is selected automatically by the system, no manual placement required!)

kubectl_configure_repository: true

kubectl_debian_repository_key: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key
kubectl_debian_repository: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /"

kubectl_redhat_repository_key: https://pkgs.k8s.io/core:/stable:/v1.28/rpm/repodata/repomd.xml.key
kubectl_redhat_repository: "https://pkgs.k8s.io/core:/stable:/v1.28/rpm/"
