---
upgrade_packages: true

required_packages_default:
  - ethtool
  - jq
  - rsyslog

required_packages_extra: []
required_packages: "{{ required_packages_default + required_packages_extra + required_packages_distribution }}"
