---
repositories: {}

repository_cache_valid_time: 120
repository_key_files_directory: ""
repository_keys: []
repository_key_ids: {}

enable_phased_updates: false

repository_apt_acquire_forceipv4: false
