---
zabbix_export:
  version: '5.2'
  date: '2021-01-09T12:54:22Z'
  groups:
    -
      name: Templates/Databases
  templates:
    -
      template: 'OSISM - MariaDB'
      name: 'OSISM - MariaDB'
      groups:
        -
          name: Templates/Databases
      applications:
        -
          name: MariaDB
        -
          name: 'MariaDB Galera Cluster'
      items:
        -
          name: 'MariaDB: aborted clients per second'
          type: TRAP
          key: 'mysql.Aborted_clients.[global]'
          delay: '0'
          value_type: FLOAT
          applications:
            -
              name: MariaDB
          preprocessing:
            -
              type: CHANGE_PER_SECOND
              parameters:
                - ''
        -
          name: 'MariaDB: aborted connects per second'
          type: TRAP
          key: 'mysql.Aborted_connects.[global]'
          delay: '0'
          value_type: FLOAT
          applications:
            -
              name: MariaDB
          preprocessing:
            -
              type: CHANGE_PER_SECOND
              parameters:
                - ''
        -
          name: 'MariaDB: bytes received per second'
          type: TRAP
          key: 'mysql.Bytes_received.[global]'
          delay: '0'
          value_type: FLOAT
          units: bps
          applications:
            -
              name: MariaDB
          preprocessing:
            -
              type: CHANGE_PER_SECOND
              parameters:
                - ''
        -
          name: 'MariaDB: bytes sent per second'
          type: TRAP
          key: 'mysql.Bytes_sent.[global]'
          delay: '0'
          value_type: FLOAT
          units: bps
          applications:
            -
              name: MariaDB
          preprocessing:
            -
              type: CHANGE_PER_SECOND
              parameters:
                - ''
        -
          name: 'MariaDB: BEGIN operations per second'
          type: TRAP
          key: 'mysql.Com_begin.[global]'
          delay: '0'
          value_type: FLOAT
          units: ops
          applications:
            -
              name: MariaDB
          preprocessing:
            -
              type: CHANGE_PER_SECOND
              parameters:
                - ''
        -
          name: 'MariaDB: COMMIT operations per second'
          type: TRAP
          key: 'mysql.Com_commit.[global]'
          delay: '0'
          value_type: FLOAT
          units: ops
          applications:
            -
              name: MariaDB
          preprocessing:
            -
              type: CHANGE_PER_SECOND
              parameters:
                - ''
        -
          name: 'MariaDB: DELETE operations per second'
          type: TRAP
          key: 'mysql.Com_delete.[global]'
          delay: '0'
          value_type: FLOAT
          units: ops
          applications:
            -
              name: MariaDB
          preprocessing:
            -
              type: CHANGE_PER_SECOND
              parameters:
                - ''
        -
          name: 'MariaDB: INSERT operations per second'
          type: TRAP
          key: 'mysql.Com_insert.[global]'
          delay: '0'
          value_type: FLOAT
          units: ops
          applications:
            -
              name: MariaDB
          preprocessing:
            -
              type: CHANGE_PER_SECOND
              parameters:
                - ''
        -
          name: 'MariaDB: ROLLBACK operations per second'
          type: TRAP
          key: 'mysql.Com_rollback.[global]'
          delay: '0'
          value_type: FLOAT
          units: ops
          applications:
            -
              name: MariaDB
          preprocessing:
            -
              type: CHANGE_PER_SECOND
              parameters:
                - ''
        -
          name: 'MariaDB: UPDATE operations per second'
          type: TRAP
          key: 'mysql.Com_update.[global]'
          delay: '0'
          value_type: FLOAT
          units: ops
          applications:
            -
              name: MariaDB
          preprocessing:
            -
              type: CHANGE_PER_SECOND
              parameters:
                - ''
        -
          name: 'Galera: get stats'
          key: 'mysql.galera.stats[{$ZABBIX_SERVER_IP},{$ZABBIX_SERVER_PORT},{$MYSQL_DSN},{$MYSQL_USER},{$MYSQL_PASS}]'
          trends: '0'
          value_type: TEXT
          applications:
            -
              name: 'MariaDB Galera Cluster'
        -
          name: 'MariaDB: get global stats'
          key: 'mysql.global.stats[{$ZABBIX_SERVER_IP},{$ZABBIX_SERVER_PORT},{$MYSQL_DSN},{$MYSQL_USER},{$MYSQL_PASS},global]'
          trends: '0'
          value_type: TEXT
          applications:
            -
              name: MariaDB
        -
          name: 'MariaDB: get process stats'
          key: 'mysql.global.stats[{$ZABBIX_SERVER_IP},{$ZABBIX_SERVER_PORT},{$MYSQL_DSN},{$MYSQL_USER},{$MYSQL_PASS},process]'
          trends: '0'
          value_type: TEXT
          applications:
            -
              name: MariaDB
        -
          name: 'MariaDB: rows DELETED per second'
          type: TRAP
          key: 'mysql.Innodb_rows_deleted.[global]'
          delay: '0'
          value_type: FLOAT
          applications:
            -
              name: MariaDB
          preprocessing:
            -
              type: CHANGE_PER_SECOND
              parameters:
                - ''
        -
          name: 'MariaDB: rows INSERTED per second'
          type: TRAP
          key: 'mysql.Innodb_rows_inserted.[global]'
          delay: '0'
          value_type: FLOAT
          applications:
            -
              name: MariaDB
          preprocessing:
            -
              type: CHANGE_PER_SECOND
              parameters:
                - ''
        -
          name: 'MariaDB: rows READ per second'
          type: TRAP
          key: 'mysql.Innodb_rows_read.[global]'
          delay: '0'
          value_type: FLOAT
          applications:
            -
              name: MariaDB
          preprocessing:
            -
              type: CHANGE_PER_SECOND
              parameters:
                - ''
        -
          name: 'MariaDB: rows UPDATED per second'
          type: TRAP
          key: 'mysql.Innodb_rows_updated.[global]'
          delay: '0'
          value_type: FLOAT
          applications:
            -
              name: MariaDB
          preprocessing:
            -
              type: CHANGE_PER_SECOND
              parameters:
                - ''
        -
          name: 'MariaDB: process count'
          type: TRAP
          key: 'mysql.processlist_count.[process]'
          delay: '0'
          applications:
            -
              name: MariaDB
        -
          name: 'MariaDB: queries per second'
          type: TRAP
          key: 'mysql.Queries.[global]'
          delay: '0'
          value_type: FLOAT
          applications:
            -
              name: MariaDB
          preprocessing:
            -
              type: CHANGE_PER_SECOND
              parameters:
                - ''
        -
          name: 'MySQL: query max time'
          type: TRAP
          key: 'mysql.query_max_time.[process]'
          delay: '0'
          applications:
            -
              name: MariaDB
        -
          name: 'MariaDB: slow queries per second'
          type: TRAP
          key: 'mysql.Slow_queries.[global]'
          delay: '0'
          value_type: FLOAT
          applications:
            -
              name: MariaDB
          preprocessing:
            -
              type: CHANGE_PER_SECOND
              parameters:
                - ''
        -
          name: 'MariaDB: running threads'
          type: TRAP
          key: 'mysql.Threads_running.[global]'
          delay: '0'
          applications:
            -
              name: MariaDB
        -
          name: 'Galera: wsrep_cluster_size'
          type: TRAP
          key: 'mysql.wsrep_cluster_size.[galera]'
          delay: '0'
          description: 'Current number of nodes in the cluster.'
          applications:
            -
              name: 'MariaDB Galera Cluster'
        -
          name: 'Galera: wsrep_cluster_state_uuid'
          type: TRAP
          key: 'mysql.wsrep_cluster_state_uuid.[galera]'
          delay: '0'
          trends: '0'
          value_type: CHAR
          description: 'This variable contains UUID state of the cluster. When this value is the same as the one in wsrep_local_state_uuid, node is synced with the cluster.'
          applications:
            -
              name: 'MariaDB Galera Cluster'
        -
          name: 'Galera: wsrep_cluster_status'
          type: TRAP
          key: 'mysql.wsrep_cluster_status.[galera]'
          delay: '0'
          trends: '0'
          value_type: CHAR
          description: |
            Status of the cluster component. Possible values are:
            * Primary
            * Non-Primary
            * Disconnected
          applications:
            -
              name: 'MariaDB Galera Cluster'
        -
          name: 'Galera: wsrep_connected'
          type: TRAP
          key: 'mysql.wsrep_connected.[galera]'
          delay: '0'
          trends: '0'
          value_type: CHAR
          description: 'This variable shows if the node is connected to the cluster. If the value is OFF, the node has not yet connected to any of the cluster components. This may be due to misconfiguration.'
          applications:
            -
              name: 'MariaDB Galera Cluster'
        -
          name: 'Galera: wsrep_evs_repl_latency.average'
          type: DEPENDENT
          key: 'mysql.wsrep_evs_repl_latency.average.[galera]'
          delay: '0'
          value_type: FLOAT
          units: s
          applications:
            -
              name: 'MariaDB Galera Cluster'
          preprocessing:
            -
              type: REGEX
              parameters:
                - (^\d+\.\d+)\/(\d+\.\d+)\/(\d+\.\d+)
                - \2
              error_handler: DISCARD_VALUE
          master_item:
            key: 'mysql.wsrep_evs_repl_latency.[galera]'
        -
          name: 'Galera: wsrep_evs_repl_latency.maximum'
          type: DEPENDENT
          key: 'mysql.wsrep_evs_repl_latency.maximum.[galera]'
          delay: '0'
          value_type: FLOAT
          units: s
          applications:
            -
              name: 'MariaDB Galera Cluster'
          preprocessing:
            -
              type: REGEX
              parameters:
                - (^\d+\.\d+)\/(\d+\.\d+)\/(\d+\.\d+)
                - \3
              error_handler: DISCARD_VALUE
          master_item:
            key: 'mysql.wsrep_evs_repl_latency.[galera]'
        -
          name: 'Galera: wsrep_evs_repl_latency.minimum'
          type: DEPENDENT
          key: 'mysql.wsrep_evs_repl_latency.minimum.[galera]'
          delay: '0'
          value_type: FLOAT
          units: s
          applications:
            -
              name: 'MariaDB Galera Cluster'
          preprocessing:
            -
              type: REGEX
              parameters:
                - (^\d+\.\d+)\/(\d+\.\d+)\/(\d+\.\d+)
                - \1
              error_handler: DISCARD_VALUE
          master_item:
            key: 'mysql.wsrep_evs_repl_latency.[galera]'
        -
          name: 'Galera: wsrep_evs_repl_latency'
          type: TRAP
          key: 'mysql.wsrep_evs_repl_latency.[galera]'
          delay: '0'
          trends: '0'
          value_type: CHAR
          description: |
            This status variable provides information regarding group communication replication latency. This latency is measured in seconds from when a message is sent out to when a message is received.
            The format of the output is <min>/<avg>/<max>/<std_dev>/<sample_size>.
          applications:
            -
              name: 'MariaDB Galera Cluster'
        -
          name: 'Galera: wsrep_evs_state'
          type: TRAP
          key: 'mysql.wsrep_evs_state.[galera]'
          delay: '0'
          trends: '0'
          value_type: CHAR
          description: 'Internal EVS protocol state.'
          applications:
            -
              name: 'MariaDB Galera Cluster'
        -
          name: 'Galera: wsrep_gcomm_uuid'
          type: TRAP
          key: 'mysql.wsrep_gcomm_uuid.[galera]'
          delay: '0'
          trends: '0'
          value_type: CHAR
          description: 'This status variable exposes UUIDs in gvwstate.dat, which are Galera view IDs (thus unrelated to cluster state UUIDs). This UUID is unique for each node. You will need to know this value when using manual eviction feature.'
          applications:
            -
              name: 'MariaDB Galera Cluster'
        -
          name: 'Galera: wsrep_last_committed.change'
          type: TRAP
          key: 'mysql.wsrep_last_committed.[galera]'
          delay: '0'
          description: 'Sequence number of the last committed transaction.'
          applications:
            -
              name: 'MariaDB Galera Cluster'
          preprocessing:
            -
              type: SIMPLE_CHANGE
              parameters:
                - ''
        -
          name: 'Galera: wsrep_local_bf_aborts'
          type: TRAP
          key: 'mysql.wsrep_local_bf_aborts.[galera]'
          delay: '0'
          description: 'Number of local transactions that were aborted by slave transactions while being executed.'
          applications:
            -
              name: 'MariaDB Galera Cluster'
        -
          name: 'Galera: wsrep_local_cert_failures'
          type: TRAP
          key: 'mysql.wsrep_local_cert_failures.[galera]'
          delay: '0'
          description: 'Number of writesets that failed the certification test.'
          applications:
            -
              name: 'MariaDB Galera Cluster'
        -
          name: 'Galera: wsrep_local_recv_queue'
          type: TRAP
          key: 'mysql.wsrep_local_recv_queue.[galera]'
          delay: '0'
          description: 'Current length of the receive queue (that is, the number of writesets waiting to be applied)'
          applications:
            -
              name: 'MariaDB Galera Cluster'
        -
          name: 'Galera: wsrep_local_recv_queue_avg'
          type: TRAP
          key: 'mysql.wsrep_local_recv_queue_avg.[galera]'
          delay: '0'
          value_type: FLOAT
          description: 'Average length of the receive queue since the last status query. When this number is bigger than 0 this means node canâ€™t apply writesets as fast as they are received. This could be a sign that the node is overloaded and it may cause replication throttling.'
          applications:
            -
              name: 'MariaDB Galera Cluster'
        -
          name: 'Galera: wsrep_local_recv_queue_max'
          type: TRAP
          key: 'mysql.wsrep_local_recv_queue_max.[galera]'
          delay: '0'
          applications:
            -
              name: 'MariaDB Galera Cluster'
        -
          name: 'Galera: wsrep_local_recv_queue_min'
          type: TRAP
          key: 'mysql.wsrep_local_recv_queue_min.[galera]'
          delay: '0'
          applications:
            -
              name: 'MariaDB Galera Cluster'
        -
          name: 'Galera: wsrep_local_send_queue'
          type: TRAP
          key: 'mysql.wsrep_local_send_queue.[galera]'
          delay: '0'
          description: 'Current length of the send queue (that is, the number of writesets waiting to be sent).'
          applications:
            -
              name: 'MariaDB Galera Cluster'
        -
          name: 'Galera: wsrep_local_send_queue_avg'
          type: TRAP
          key: 'mysql.wsrep_local_send_queue_avg.[galera]'
          delay: '0'
          value_type: FLOAT
          description: 'Average length of the send queue since the last status query. When cluster experiences network throughput issues or replication throttling, this value will be significantly bigger than 0.'
          applications:
            -
              name: 'MariaDB Galera Cluster'
        -
          name: 'Galera: wsrep_local_send_queue_max'
          type: TRAP
          key: 'mysql.wsrep_local_send_queue_max.[galera]'
          delay: '0'
          applications:
            -
              name: 'MariaDB Galera Cluster'
        -
          name: 'Galera: wsrep_local_send_queue_min'
          type: TRAP
          key: 'mysql.wsrep_local_send_queue_min.[galera]'
          delay: '0'
          applications:
            -
              name: 'MariaDB Galera Cluster'
        -
          name: 'Galera: wsrep_local_state_comment'
          type: TRAP
          key: 'mysql.wsrep_local_state_comment.[galera]'
          delay: '0'
          trends: '0'
          value_type: CHAR
          applications:
            -
              name: 'MariaDB Galera Cluster'
        -
          name: 'Galera: wsrep_local_state_uuid'
          type: TRAP
          key: 'mysql.wsrep_local_state_uuid.[galera]'
          delay: '0'
          trends: '0'
          value_type: CHAR
          description: 'The UUID of the state stored on the node.'
          applications:
            -
              name: 'MariaDB Galera Cluster'
        -
          name: 'Galera: wsrep_protocol_version'
          type: TRAP
          key: 'mysql.wsrep_protocol_version.[galera]'
          delay: '0'
          description: 'Version of the wsrep protocol used.'
          applications:
            -
              name: 'MariaDB Galera Cluster'
        -
          name: 'Galera: wsrep_provider_name'
          type: TRAP
          key: 'mysql.wsrep_provider_name.[galera]'
          delay: '0'
          trends: '0'
          value_type: CHAR
          description: 'Name of the wsrep provider (usually Galera).'
          applications:
            -
              name: 'MariaDB Galera Cluster'
        -
          name: 'Galera: wsrep_ready'
          type: TRAP
          key: 'mysql.wsrep_ready.[galera]'
          delay: '0'
          trends: '0'
          value_type: CHAR
          description: 'This variable shows if node is ready to accept queries. If status is OFF, almost all queries will fail with ERROR 1047 (08S01) Unknown Command error (unless the wsrep_on variable is set to 0).'
          applications:
            -
              name: 'MariaDB Galera Cluster'
        -
          name: 'MariaDB: number of running mysql processes'
          key: 'proc.num[,,,mysqld]'
          applications:
            -
              name: MariaDB
      macros:
        -
          macro: '{$MAX_PROCESSES}'
          value: '100'
        -
          macro: '{$MYSQL_DSN}'
          value: 'localhost:3306'
        -
          macro: '{$MYSQL_MAX_QUERY_TIME}'
          value: '60'
        -
          macro: '{$MYSQL_PASS}'
          value: zabbix
        -
          macro: '{$MYSQL_USER}'
          value: zabbix
