---
- name: Wait for apt lock
  shell: while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done

- name: Ensure docker-compose is not installed
  become: true
  apt:
    name: docker-compose
    state: absent

- name: Block installation of docker-compose package
  become: true
  copy:
    content: |
      Package: docker-compose
      Pin: version *
      Pin-Priority: -1
    mode: 0644
    dest: /etc/apt/preferences.d/docker-compose

- name: Download docker-compose binary
  become: true
  get_url:
    url: "{{ docker_compose_url }}"
    dest: /usr/local/bin/docker-compose
    owner: root
    group: root
    mode: 0755

- name: Get checksum of docker-compose binary
  stat:
    path: /usr/local/bin/docker-compose
    checksum_algorithm: sha256
  register: p

- name: Check checksum of docker-compose binary
  fail:
    msg: "Expected checksum of docker-compose does not match"
  when:
    - "p.stat.checksum != docker_compose_checksum"
