---
name: Test role cleanup

"on":
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/test-role-cleanup.yml'
      - 'molecule/default/*'
      - 'molecule/cleanup/**'
      - 'roles/cleanup/**'
  pull_request:
    paths:
      - '.github/workflows/test-role-cleanup.yml'
      - 'molecule/default/*'
      - 'molecule/cleanup/**'
      - 'roles/cleanup/**'

jobs:
  test-role-cleanup:

    runs-on: ubuntu-latest

    env:
      ANSIBLE_ROLE: cleanup

    strategy:
      max-parallel: 4
      matrix:
        ansible-version: ['2.11.6']
        python-version: ['3.8']
        docker-image: ['ubuntu:20.04']

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      # NOTE: Technically, Molecule supports variable interpolation in molecule.yml.
      #       For reasons that are not really comprehensible, however, it does not
      #       work here. Hence this workaround.
      - name: Prepare molecule.yml
        run: |
          sed -i "s/\${DOCKER_IMAGE}/${{ matrix.docker-image }}/g" molecule/default/molecule.yml
          sed -i "s/\${ANSIBLE_ROLE}/${{ env.ANSIBLE_ROLE }}/g" molecule/default/molecule.yml
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r molecule/requirements.txt
          python3 -m pip install ansible-core~=${{ matrix.ansible-version }}
      - name: Run molecule
        run: molecule test -s default
      - name: Cleanup molecule
        run: molecule destroy -s default
        if: ${{ always() }}
